# Generated by Django 3.2 on 2021-05-01 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0003_alter_good_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
